name: Dependency Check
on: workflow_dispatch
jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@master
      - name: Run Dependency Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.3.1/dependency-check-8.3.1-release.zip
          unzip dependency-check-8.3.1-release.zip
          ./dependency-check/bin/dependency-check.sh --project "My Project" --scan ./ --out . --format "SARIF"

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./dependency-check-sarif.json
